### ISSUE TITLE
maximum recursion depth exceeded

### ISSUE THREAD

**Issue by mgafner** [jpbarraca/mail-trends#4]
with a mail count more than ~ 26'000 Mails I get this error:

``` python
[2014-12-10 11:11:21,359] Extracting threads
Traceback (most recent call last):
  File "./main.py", line 291, in <module>
    threads = ExtractThreads(message_infos)
  File "./main.py", line 199, in ExtractThreads
    thread_dict = jwzthreading.thread(thread_messages)
  File "git/mail-trends/jwzthreading.py", line 185, in thread
    prev.add_child(this_container)
  File "git/mail-trends/jwzthreading.py", line 32, in add_child
    if child.parent:
  File "git/mail-trends/jwzthreading.py", line 54, in __len__
    count += len(c)
  File "git/mail-trends/jwzthreading.py", line 54, in __len__
    count += len(c)
[...]
  File "git/mail-trends/jwzthreading.py", line 54, in __len__
    count += len(c)
  File "git/mail-trends/jwzthreading.py", line 54, in __len__
    count += len(c)
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

**Comment by gsever** [comment]
I get the same error. Is there any fix available for this issue?

**Comment by jpbarraca** [comment]
Should be fixed by now.

**Comment by gsever** [comment]
I still see errors on the fixed version, starting with:

File main.py, line 73, in GetOptsMap
    return op
NameError: global name 'op' is not defined.

**Comment by jpbarraca** [comment]
fixed the typo

**Comment by gsever** [comment]
Still errors:

[2016-07-22 08:13:59,493] Selecting mailbox '[Gmail]'
Traceback (most recent call last):
  File "main.py", line 304, in <module>
    message_infos = GetMessageInfos(opts)
  File "main.py", line 109, in GetMessageInfos
    m.SelectMailbox(mailbox)
  File "C:\mail-trends-master\mail.py", line 66, in SelectMailbox
    self.__AssertOk(r)
  File "C:\mail-trends-master\mail.py", line 191, in __AssertOk
    assert response == "OK"
AssertionError

Do you see these errors using the master branch?

**Comment by gsever** [comment]
I think I tricked the program to get it working:

in mail.py (to eliminate the above assertion error):
mailboxes.remove('[Gmail]')
then (to eliminate imaplib.readonly: [Gmail]/Chats is not writable error)
mailboxes.remove('[Gmail]/Chats')

html is written under out folder, output looks good.
Based on 8311 threads (54605 messages) between October 11 2007 and July 22 2016.

**Comment by gsever** [comment]
one more update, fixed the readonly error by changing:
r, data = self.__mail.select(mailbox, readonly=True)
so it can fetch messages from '[Gmail]/Chats' folder as well.

**Comment by jpbarraca** [comment]
I didn't test that last commit with GMAIL. Tks for the help.

**Comment by jpbarraca** [comment]
You wish to create a PR?

**Comment by gsever** [comment]
These are only two minor fixes.
1- mail.py,  Line 62 
add:
mailboxes.remove('[Gmail]')

2- then line 67
update:
r, data = self.__mail.select(mailbox, readonly=True)

this should do the job.

**Comment by jpbarraca** [comment]
The purpose was to effectively connect you to the changes added to the tree, giving you credit for the help.

**Comment by mgafner** [comment]
Thanks a lot! This works now with 100'000 Mails!

**Comment by jpbarraca** [comment]
tested with +200.000 Mails. It takes a lot of time, but it works.
